#!/bin/bash

# SOMI Sentinel Complete Demo Script
# This script demonstrates the full integration flow

set -e

echo "🎬 SOMI Sentinel Complete Demo"
echo "============================="

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

print_demo() {
    echo -e "${PURPLE}[DEMO]${NC} $1"
}

print_step() {
    echo -e "${CYAN}[STEP]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Function to wait for user input
wait_for_user() {
    echo ""
    read -p "Press Enter to continue..." -r
    echo ""
}

# Function to check if service is running
check_service() {
    local service_name="$1"
    local url="$2"
    
    if curl -s "$url" > /dev/null 2>&1; then
        return 0
    else
        return 1
    fi
}

# Function to display service status
show_service_status() {
    local service_name="$1"
    local url="$2"
    
    if check_service "$service_name" "$url"; then
        print_success "$service_name is running"
    else
        print_error "$service_name is not running"
        return 1
    fi
}

# Function to make API call and display result
api_call() {
    local url="$1"
    local description="$2"
    
    print_info "Making API call: $description"
    echo "URL: $url"
    
    local response=$(curl -s "$url")
    echo "Response:"
    echo "$response" | jq . 2>/dev/null || echo "$response"
    echo ""
}

# Function to simulate agent activity
simulate_agent_activity() {
    print_demo "Simulating Agent Activity..."
    
    # Check agent status
    api_call "http://localhost:3002/status" "Agent Status"
    
    # Simulate a proposal (this would normally be generated by the agent)
    print_info "Agent would normally:"
    echo "1. Monitor blockchain for market signals"
    echo "2. Detect price volatility or oracle drift"
    echo "3. Simulate potential actions"
    echo "4. Generate AI rationale using Gemini"
    echo "5. Upload simulation report to IPFS"
    echo "6. Sign proposal with private key"
    echo "7. Send to relayer for execution"
    
    wait_for_user
}

# Function to simulate relayer activity
simulate_relayer_activity() {
    print_demo "Simulating Relayer Activity..."
    
    # Check relayer status
    api_call "http://localhost:3001/status" "Relayer Status"
    
    print_info "Relayer would normally:"
    echo "1. Receive signed proposal from agent"
    echo "2. Verify ECDSA signature"
    echo "3. Check proposal nonce and deadline"
    echo "4. Estimate gas for transaction"
    echo "5. Submit transaction to Executor contract"
    echo "6. Monitor transaction status"
    echo "7. Return transaction hash to agent"
    
    wait_for_user
}

# Function to show contract interaction
show_contract_interaction() {
    print_demo "Contract Interaction Demo..."
    
    if [ -f "deployed.json" ]; then
        print_info "Deployed Contracts:"
        echo "Vault: $(cat deployed.json | jq -r '.contracts.vault')"
        echo "Executor: $(cat deployed.json | jq -r '.contracts.executor')"
        echo "Policy Manager: $(cat deployed.json | jq -r '.contracts.policyManager')"
        echo "Audit Log: $(cat deployed.json | jq -r '.contracts.auditLog')"
        echo ""
        
        print_info "Contract Flow:"
        echo "1. Executor receives proposal from relayer"
        echo "2. Executor verifies agent signature"
        echo "3. Executor checks policy compliance"
        echo "4. Executor calls Vault.executeAction()"
        echo "5. Vault executes the action (swap, lend, etc.)"
        echo "6. AuditLog records the execution"
        echo "7. Events are emitted for monitoring"
    else
        print_warning "No contract deployment found"
    fi
    
    wait_for_user
}

# Function to show frontend integration
show_frontend_integration() {
    print_demo "Frontend Integration Demo..."
    
    # Show vault data
    api_call "http://localhost:3000/api/vaults" "Vault List"
    
    # Show individual vault
    api_call "http://localhost:3000/api/vaults/1" "Vault Details"
    
    # Show proposal data
    api_call "http://localhost:3000/api/proposals/0xabcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890" "Proposal Details"
    
    print_info "Frontend Features:"
    echo "1. Real-time vault monitoring"
    echo "2. Policy management interface"
    echo "3. System status dashboard"
    echo "4. Proposal history and details"
    echo "5. Risk assessment visualization"
    echo "6. Transaction history"
    
    wait_for_user
}

# Function to show complete flow
show_complete_flow() {
    print_demo "Complete Integration Flow Demo..."
    
    echo "🔄 End-to-End Flow:"
    echo "=================="
    echo ""
    echo "1. 📊 Market Monitoring"
    echo "   Agent continuously monitors blockchain for:"
    echo "   - Price volatility"
    echo "   - Oracle drift"
    echo "   - Liquidity changes"
    echo "   - Volume spikes"
    echo ""
    
    echo "2. 🤖 AI Analysis"
    echo "   When signals are detected:"
    echo "   - Agent simulates potential actions"
    echo "   - Generates AI rationale using Gemini"
    echo "   - Calculates risk scores and outcomes"
    echo "   - Uploads detailed report to IPFS"
    echo ""
    
    echo "3. 🔐 Proposal Generation"
    echo "   Agent creates signed proposal:"
    echo "   - Encodes action parameters"
    echo "   - Includes IPFS hash of simulation"
    echo "   - Signs with ECDSA private key"
    echo "   - Includes nonce and deadline"
    echo ""
    
    echo "4. ⚡ Transaction Execution"
    echo "   Relayer processes proposal:"
    echo "   - Verifies signature authenticity"
    echo "   - Checks nonce for replay protection"
    echo "   - Estimates gas costs"
    echo "   - Submits to Executor contract"
    echo ""
    
    echo "5. 🛡️ Policy Validation"
    echo "   Executor contract validates:"
    echo "   - Agent signature matches registered signer"
    echo "   - Proposal hasn't expired"
    echo "   - Action complies with vault policy"
    echo "   - Risk tolerance is respected"
    echo ""
    
    echo "6. 💰 Action Execution"
    echo "   Vault executes the action:"
    echo "   - Calls appropriate protocol adapter"
    echo "   - Executes swap, lend, or other action"
    echo "   - Updates vault balances"
    echo "   - Emits execution events"
    echo ""
    
    echo "7. 📝 Audit Trail"
    echo "   System records execution:"
    echo "   - AuditLog stores proposal details"
    echo "   - IPFS hash links to full report"
    echo "   - Transaction hash for verification"
    echo "   - Timestamp and executor address"
    echo ""
    
    echo "8. 🖥️ Frontend Updates"
    echo "   User interface reflects changes:"
    echo "   - Backend fetches updated contract data"
    echo "   - Frontend displays new vault state"
    echo "   - Shows execution history"
    echo "   - Updates risk metrics"
    echo ""
    
    wait_for_user
}

# Main demo execution
main() {
    print_demo "Welcome to the SOMI Sentinel Complete Integration Demo!"
    echo ""
    echo "This demo will show you how all components work together:"
    echo "• Frontend (React) - User interface"
    echo "• Backend API (Express) - Data bridge"
    echo "• Agent (Node.js) - AI monitoring"
    echo "• Relayer (Express) - Transaction execution"
    echo "• Contracts (Solidity) - On-chain logic"
    echo ""
    
    wait_for_user
    
    # Check if all services are running
    print_step "Step 1: Checking Service Status"
    echo "=================================="
    
    show_service_status "Backend API" "http://localhost:3000/health"
    show_service_status "Relayer" "http://localhost:3001/health"
    show_service_status "Agent" "http://localhost:3002/status"
    show_service_status "Frontend" "http://localhost:5173"
    
    wait_for_user
    
    # Show system architecture
    print_step "Step 2: System Architecture Overview"
    echo "======================================="
    
    echo "🏗️ System Components:"
    echo ""
    echo "Frontend (Port 5173) ←→ Backend API (Port 3000) ←→ Blockchain"
    echo "                           ↑"
    echo "Agent (Port 3002) ←→ Relayer (Port 3001) ←→ Executor Contract"
    echo ""
    echo "Data Flow:"
    echo "1. Agent monitors blockchain"
    echo "2. Agent generates proposals"
    echo "3. Relayer executes transactions"
    echo "4. Backend aggregates data"
    echo "5. Frontend displays results"
    
    wait_for_user
    
    # Show contract integration
    print_step "Step 3: Contract Integration"
    echo "=============================="
    show_contract_interaction
    
    # Show agent activity
    print_step "Step 4: Agent Service Demo"
    echo "============================="
    simulate_agent_activity
    
    # Show relayer activity
    print_step "Step 5: Relayer Service Demo"
    echo "==============================="
    simulate_relayer_activity
    
    # Show frontend integration
    print_step "Step 6: Frontend Integration Demo"
    echo "==================================="
    show_frontend_integration
    
    # Show complete flow
    print_step "Step 7: Complete Integration Flow"
    echo "===================================="
    show_complete_flow
    
    # Final summary
    print_step "Step 8: Demo Summary"
    echo "======================"
    
    print_success "Demo Complete! 🎉"
    echo ""
    echo "✅ All components are integrated and working together"
    echo "✅ Real-time data flows from blockchain to frontend"
    echo "✅ AI agent monitors and responds to market conditions"
    echo "✅ Relayer executes transactions securely"
    echo "✅ Complete audit trail is maintained"
    echo ""
    echo "🌐 Access the application:"
    echo "Frontend: http://localhost:5173"
    echo "Backend:  http://localhost:3000/health"
    echo "Relayer:  http://localhost:3001/status"
    echo "Agent:    http://localhost:3002/status"
    echo ""
    echo "📊 Monitor the system:"
    echo "bash scripts/check-status.sh"
    echo ""
    echo "🧪 Run integration tests:"
    echo "bash scripts/test-integration.sh"
    echo ""
    echo "🛑 Stop all services:"
    echo "bash scripts/stop-all.sh"
    echo ""
    print_demo "Thank you for exploring SOMI Sentinel! 🚀"
}

# Run the demo
main
